# Generated by Django 3.2.25 on 2025-08-30 18:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumanLabelingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('strategy', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_samples', models.IntegerField(default=0)),
                ('labeled_samples', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('batch_size', models.IntegerField(default=1)),
                ('target_accuracy', models.FloatField(blank=True, null=True)),
                ('max_samples', models.IntegerField(default=100)),
                ('current_accuracy', models.FloatField(blank=True, null=True)),
                ('initial_accuracy', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samples_labeled', models.IntegerField()),
                ('test_accuracy', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to='project2.humanlabelingsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HumanLabeledSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_text', models.TextField()),
                ('sample_index', models.IntegerField()),
                ('human_label', models.IntegerField(blank=True, choices=[(0, 'Negative'), (1, 'Positive')], null=True)),
                ('ground_truth_label', models.IntegerField(choices=[(0, 'Negative'), (1, 'Positive')])),
                ('labeled_at', models.DateTimeField(blank=True, null=True)),
                ('uncertainty_score', models.FloatField(blank=True, null=True)),
                ('selection_order', models.IntegerField(default=0)),
                ('labeling_time_seconds', models.FloatField(blank=True, null=True)),
                ('confidence', models.IntegerField(blank=True, choices=[(1, 'Very Unsure'), (2, 'Unsure'), (3, 'Neutral'), (4, 'Sure'), (5, 'Very Sure')], null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='project2.humanlabelingsession')),
            ],
            options={
                'ordering': ['selection_order'],
                'unique_together': {('session', 'sample_index')},
            },
        ),
    ]
