# Generated by Django 3.2.25 on 2025-08-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanlabeledsample',
            name='sample_original_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
