# Generated by Django 3.2.25 on 2025-08-08 15:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_to', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('familiarity', models.IntegerField()),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project4.participant')),
            ],
        ),
        migrations.CreateModel(
            name='PostSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust', models.IntegerField()),
                ('transparency', models.IntegerField()),
                ('satisfaction', models.IntegerField()),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project4.participant')),
            ],
        ),
        migrations.CreateModel(
            name='HeldOutRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('rating', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project4.participant')),
            ],
        ),
    ]
