# Generated by Django 3.2.25 on 2025-08-31 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='display_name',
            field=models.CharField(default='Participant', max_length=100),
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_vector', models.TextField()),
                ('final_rmse', models.FloatField(blank=True, null=True)),
                ('completion_status', models.CharField(default='in_progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project4.participant')),
            ],
        ),
        migrations.CreateModel(
            name='QuizRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('rating', models.FloatField()),
                ('iteration', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('explanation_shown', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project4.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpfulness', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project4.participant')),
            ],
        ),
    ]
